# .github/workflows/build.yml
name: Build FirEnchant Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Ensure Gradle wrapper is executable
        run: |
          # 确保 gradlew 有执行权限（关键修复）
          chmod +x ./gradlew
          # 验证权限设置
          ls -l ./gradlew

      - name: Build with Gradle
        run: ./gradlew build shadowJar
        env:
          # 可选：增加内存分配以避免大型项目构建失败
          GRADLE_OPTS: "-Xmx2g -Dorg.gradle.daemon=false"

      - name: Locate built JAR
        run: |
          # 验证构建产物是否存在
          echo "查找构建的JAR文件..."
          ls -l ${{ github.workspace }}/target

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firenchant-plugin
          path: ${{ github.workspace }}/target/*.jar
          retention-days: 7  # 保留7天便于下载

  # 完全移除依赖图提交步骤，因为仓库未启用该功能
  # 如需启用，请先在仓库设置中开启 Dependency graph
